repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version - use `pre-commit autoupdate --freeze` to update
    rev: f298305809c552671cc47e0fec0ba43e96c146a2  # frozen: v0.13.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    # MyPy version - use `pre-commit autoupdate --freeze` to update
    rev: 9f70dc58c23dfcca1b97af99eaeee3140a807c7e  # frozen: v1.18.2
    hooks:
      - id: mypy
        pass_filenames: true
        require_serial: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    # Pre-commit hooks version - use `pre-commit autoupdate --freeze` to update
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
        args: [--fix=lf]
