repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version - use `pre-commit autoupdate --freeze` to update
    rev: db90487f48a9dd992d243ef63c156eaffddeaf28  # frozen: v0.12.11
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    # MyPy version - use `pre-commit autoupdate --freeze` to update
    rev: 412de98d50e846f31ea6f4b0ad036f2c24a7a024  # frozen: v1.17.1
    hooks:
      - id: mypy
        pass_filenames: true
        require_serial: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    # Pre-commit hooks version - use `pre-commit autoupdate --freeze` to update
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
        args: [--fix=lf]
